pipeline {
    agent {
        label 'dev'
    }

    stages {
        stage('clone') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Manohar7104/terraform.git'
            }
        }
    }
}